### Exercise 7

Read the Colleges dataset and clean all the numeric attributes.\
From all marks based attributes, remove % sign from different attributes. In SAT/ACT column, Keep higher value.\
From all cost based attributes, Remove $ sign and commas.\
Remove any null value in any attribute.

In [1]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv("../../datasets/Top 100 Private Colleges.2003.csv")
df.set_index("Overall Rank", inplace=True)
df.head(10)

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4.0
2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5.0
3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21.0
5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38.0
6.0,Webb Institute,NY,67.0,42%,100/100%,7.0,79%,83%,39.0,"$8,079","$5,579",20%,100%,"$8,079",100%,"$5,700",1.0
7.0,Yale University,CT,5339.0,8%,96/97%,7.0,88%,95%,3.0,"$38,432","$15,729",100%,89%,"$38,432",NaN,"$19,228",53.0
8.0,Washington and Lee University,VA,1750.0,31%,89/89%,11.0,86%,89%,30.0,"$30,225","$15,452",99%,87%,"$22,063",31%,"$15,634",9.0
9.0,Harvard University,MA,6637.0,11%,90*/90*%,8.0,86%,97%,8.0,"$38,831","$17,456",100%,90%,"$33,201",NaN,"$10,465",46.0
10.0,Stanford University,CA,7360.0,13%,93/95%,7.0,77%,93%,6.0,"$38,875","$17,746",100%,86%,"$33,709",NaN,"$15,782",62.0

In [48]:
df.isnull().sum() / len(df) * 100

School                            1.960784
State                             1.960784
Undergrad. Enrollment             1.960784
Admission Rate                    1.960784
*SAT or ACT                       1.960784
Student/faculty Ratio             1.960784
4-year Grad. Rate                 1.960784
6-year Grad. Rate                 1.960784
Quality Rank                      1.960784
Total Costs                       1.960784
Cost After Need-based Aid         1.960784
Need Met                          1.960784
Aid From Grants                   1.960784
Cost After Non-Need-Based Aid     1.960784
Non-Need-Based Aid+              28.431373
Average Debt                      1.960784
Cost Rank                         1.960784
dtype: float64

In [49]:
df.dtypes

School                               str
State                                str
Undergrad. Enrollment            float64
Admission Rate                       str
*SAT or ACT                          str
Student/faculty Ratio            float64
4-year Grad. Rate                    str
6-year Grad. Rate                    str
Quality Rank                     float64
Total Costs                          str
Cost After Need-based Aid            str
Need Met                             str
Aid From Grants                      str
Cost After Non-Need-Based Aid        str
Non-Need-Based Aid+                  str
Average Debt                         str
Cost Rank                        float64
dtype: object

In [50]:
to_drop = []
cols = df.columns

na_ratio = df.isnull().sum() / len(df) * 100

for i in range(len(cols)):
    if na_ratio.values[i] >= 20:
        to_drop.append(cols[i])

print(to_drop)

['Non-Need-Based Aid+']

In [51]:
df.drop(to_drop, axis=1, inplace=True)
print(list(c for c in df.columns if c in to_drop))

[]

In [52]:
has_some_missing = []
cols = df.columns

na_ratio = df.isnull().sum() / len(df) * 100

for i in range(len(cols)):
    if na_ratio.values[i] >= 0:
        has_some_missing.append(cols[i])

print(has_some_missing)

['School', 'State', 'Undergrad. Enrollment', 'Admission Rate', '*SAT or ACT', 'Student/faculty Ratio', '4-year Grad. Rate', '6-year Grad. Rate', 'Quality Rank', 'Total Costs', 'Cost After Need-based Aid', 'Need Met', 'Aid From Grants', 'Cost After Non-Need-Based Aid', 'Average Debt', 'Cost Rank']

In [60]:
new_df = df.dropna(axis=0)
print(f"{len(new_df)}/{len(df)}")

100/102

In [61]:
new_df.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553","$10,244",4.0
2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418","$12,705",5.0
3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251","$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404","$12,759",21.0
5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411","$11,544",38.0

In [62]:
new_df.isnull().sum() / len(new_df) * 100

School                           0.0
State                            0.0
Undergrad. Enrollment            0.0
Admission Rate                   0.0
*SAT or ACT                      0.0
Student/faculty Ratio            0.0
4-year Grad. Rate                0.0
6-year Grad. Rate                0.0
Quality Rank                     0.0
Total Costs                      0.0
Cost After Need-based Aid        0.0
Need Met                         0.0
Aid From Grants                  0.0
Cost After Non-Need-Based Aid    0.0
Average Debt                     0.0
Cost Rank                        0.0
dtype: float64

In [63]:
col_with_percent = [
    "Admission Rate",
    "4-year Grad. Rate",
    "6-year Grad. Rate",
    "Need Met",
    "Aid From Grants",
]


def clean_percent(inp):
    if "%" in inp:
        inp = inp[: inp.find("%")]

    if inp.lower() == "na":
        return np.nan
    return inp


for col in col_with_percent:
    new_df[col] = new_df[col].apply(clean_percent).astype(np.float64)

new_df.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21.0,99/100%,3.0,71.0,85.0,10.0,"$32,682","$10,981",100.0,93.0,"$18,553","$10,244",4.0
2.0,Rice University,TX,2787.0,24.0,89/92%,5.0,68.0,89.0,19.0,"$28,350","$14,779",100.0,88.0,"$22,418","$12,705",5.0
3.0,Williams College,MA,1985.0,23.0,93/93%,8.0,89.0,94.0,1.0,"$36,550","$14,737",100.0,89.0,"$33,251","$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24.0,94/98%,8.0,86.0,92.0,4.0,"$38,676","$17,386",100.0,85.0,"$11,404","$12,759",21.0
5.0,Amherst College,MA,1618.0,18.0,94/92%,9.0,84.0,94.0,5.0,"$38,492","$14,453",100.0,92.0,"$33,411","$11,544",38.0

In [64]:
new_df.dtypes

School                               str
State                                str
Undergrad. Enrollment            float64
Admission Rate                   float64
*SAT or ACT                          str
Student/faculty Ratio            float64
4-year Grad. Rate                float64
6-year Grad. Rate                float64
Quality Rank                     float64
Total Costs                          str
Cost After Need-based Aid            str
Need Met                         float64
Aid From Grants                  float64
Cost After Non-Need-Based Aid        str
Average Debt                         str
Cost Rank                        float64
dtype: object

In [65]:
unwanted = ["%", "*"]


def remove_unwanted(inp):
    for uw in unwanted:
        inp = inp.replace(uw, "")
    return inp


def clean_sat_act(inp):
    if "/" in inp:
        sat, act = inp.split("/")
        act = float(remove_unwanted(act))
        sat = float(remove_unwanted(sat))
        return max(sat, act)
    else:
        return float(remove_unwanted(inp))


new_df["*SAT or ACT"] = new_df["*SAT or ACT"].apply(clean_sat_act).astype(np.float64)

In [66]:
new_df.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21.0,100.0,3.0,71.0,85.0,10.0,"$32,682","$10,981",100.0,93.0,"$18,553","$10,244",4.0
2.0,Rice University,TX,2787.0,24.0,92.0,5.0,68.0,89.0,19.0,"$28,350","$14,779",100.0,88.0,"$22,418","$12,705",5.0
3.0,Williams College,MA,1985.0,23.0,93.0,8.0,89.0,94.0,1.0,"$36,550","$14,737",100.0,89.0,"$33,251","$12,316",26.0
4.0,Swarthmore College,PA,1479.0,24.0,98.0,8.0,86.0,92.0,4.0,"$38,676","$17,386",100.0,85.0,"$11,404","$12,759",21.0
5.0,Amherst College,MA,1618.0,18.0,94.0,9.0,84.0,94.0,5.0,"$38,492","$14,453",100.0,92.0,"$33,411","$11,544",38.0

In [67]:
col_with_dollar = [
    "Total Costs",
    "Cost After Need-based Aid",
    "Cost After Non-Need-Based Aid",
    "Average Debt",
]

unwanted_dollar = [",", "$"]


def clean_dollar(inp):
    for uw in unwanted_dollar:
        inp = inp.replace(uw, "")
    return inp


for col in col_with_dollar:
    new_df[col] = new_df[col].apply(clean_dollar).astype(np.float64)

new_df.head()

,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
Overall Rank,,,,,,,,,,,,,,,,
1.0,California Institute of Technology,CA,939.0,21.0,100.0,3.0,71.0,85.0,10.0,32682.0,10981.0,100.0,93.0,18553.0,10244.0,4.0
2.0,Rice University,TX,2787.0,24.0,92.0,5.0,68.0,89.0,19.0,28350.0,14779.0,100.0,88.0,22418.0,12705.0,5.0
3.0,Williams College,MA,1985.0,23.0,93.0,8.0,89.0,94.0,1.0,36550.0,14737.0,100.0,89.0,33251.0,12316.0,26.0
4.0,Swarthmore College,PA,1479.0,24.0,98.0,8.0,86.0,92.0,4.0,38676.0,17386.0,100.0,85.0,11404.0,12759.0,21.0
5.0,Amherst College,MA,1618.0,18.0,94.0,9.0,84.0,94.0,5.0,38492.0,14453.0,100.0,92.0,33411.0,11544.0,38.0

In [68]:
new_df.dtypes

School                               str
State                                str
Undergrad. Enrollment            float64
Admission Rate                   float64
*SAT or ACT                      float64
Student/faculty Ratio            float64
4-year Grad. Rate                float64
6-year Grad. Rate                float64
Quality Rank                     float64
Total Costs                      float64
Cost After Need-based Aid        float64
Need Met                         float64
Aid From Grants                  float64
Cost After Non-Need-Based Aid    float64
Average Debt                     float64
Cost Rank                        float64
dtype: object