## This Notebook is used to understand Pandas module
### This is Part 1 of the Pandas Notebook
Dr. Naveen Aggarwal

#### Panel + Data = Pandas
<li> It provides well-defined data structures and their functions.<BR>
<li> It translates complex operations by using simple commands.<BR>
<li> Easy to group, filtering, concatenating data, Well, organized way of doing time-series functionality.<BR>
<li> Sorting, Aggregations, Indexing and re-indexing, and Iterations.<BR>
<li> Reshape the data and its structure,<BR>
<li> Quick slice, and dice the data based on our necessity.<BR>
<li> Data manipulation capabilities are very similar to SQL.<BR>
<li> Handling data for various aspects like missing data, cleaning, and manipulating data is with a simple line of code.<BR>
   
Since it has very powerful it can handle Tabular data, Ordered and Unordered time series data, and fit for Un-labelled data.

In [1]:
import numpy as np
import pandas as pd

### Creating Structured Array using np array

In [ ]:
# A structured array
# Structured arrays allow users to manipulate the data by named fields:
# in the example below, a structured array of three tuples is created.
# The first element of each tuple will be called ‘first’ and will be of type int,
# while the second element will be named ‘second’ and will be a float.
my_array = np.ones(3, dtype=([("first", int), ("second", float)]))
# Print the structured array
print(my_array)
print(my_array["first"])
print(my_array["second"])

[(1, 1.) (1, 1.) (1, 1.)]
[1 1 1]
[1. 1. 1.]

In [3]:
# A record array
my_array2 = my_array.view(np.recarray)
# Print the record array
print(my_array2)
print(my_array2.first[0])
print(my_array2.second)

[(1, 1.) (1, 1.) (1, 1.)]
1
[1. 1. 1.]

#### Series and DataFrame
“Series” and “DataFrame” are the primary “Data Structures” components of pandas. Series is a kind of dictionary and collection of series, if you merging the series, we could construct the dataframe. Data Frame is a structured dataset, and you can play with that.

##### Series
One Dimensional Array with Fixed Length.
##### DataFrame
<li>Two-Dimensional Array
<li>Fixed Length
<li>Rectangular table of data (Column and Rows)

### Creating a Series by passing a list of values, letting pandas create a default integer index

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)
dates = pd.date_range("20130101", periods=6)
print(dates)
print(dates.year, dates.month, dates.day)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index([2013, 2013, 2013, 2013, 2013, 2013], dtype='int32') Index([1, 1, 1, 1, 1, 1], dtype='int32') Index([1, 2, 3, 4, 5, 6], dtype='int32')

### Creating Dataframe using dictionary

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.605608  2.239424 -1.972249  1.202611
2013-01-02 -0.950039  1.268141  1.562293 -1.274266
2013-01-03  2.022518  0.993316  0.427421 -2.267654
2013-01-04 -0.747721 -2.141370 -0.548205  1.223524
2013-01-05  0.424063 -1.236719  0.954442 -0.171687
2013-01-06  1.103227  0.900754  2.831636  0.272540

### Creating Dataframe from np array

In [ ]:
data = np.array([["", "Col1", "Col2"], ["Row1", 1, 2], ["Row2", 3, 4]])

print(pd.DataFrame(data=data[1:, 1:], index=data[1:, 0], columns=data[0, 1:]))
# df=pd.DataFrame(data=data[1:,1:],
#                  index=data[1:,0],
#                  columns=data[0,1:])
# print(df.index)
# print(df.columns)
# print(df)

     Col1 Col2
Row1    1    2
Row2    3    4

### Creating a DataFrame by passing a dict of objects that can be converted to series-like.

In [ ]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=range(5), dtype="float32"),
        "D": np.array([3] * 5, dtype="int32"),
        "E": "foo",
    }
)
print(df2)
df2.dtypes

     A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo
4  1.0 2013-01-02  1.0  3  foo

A          float64
B    datetime64[s]
C          float32
D            int32
E           object
dtype: object

### Creating Dataframes from array, dictionary and series

In [ ]:
# Take a 2D array as input to your DataFrame
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print("Data Frame From Array\n", pd.DataFrame(my_2darray))

Data Frame From Array
    0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Take a dictionary as input to your DataFrame
my_dict = {"A": ["1", "3"], "B": ["1", "2"], 3: ["2", "4"]}
print("Data Frame From Dictionary\n", pd.DataFrame(my_dict))

Data Frame From Dictionary
    A  B  3
0  1  1  2
1  3  2  4

In [ ]:
# Take a DataFrame as input to your DataFrame
my_df = pd.DataFrame(data=[4, 5, 6, 7], index=range(0, 4), columns=["A"])
print("Data Frame From another dataframe\n", pd.DataFrame(my_df))

Data Frame From another dataframe
    A
0  4
1  5
2  6
3  7

In [ ]:
# Take a Series as input to your DataFrame
my_series = pd.Series({"United Kingdom": "London", "India": "New Delhi"})
print("Data Frame From Series\n", pd.DataFrame(my_series))

Data Frame From Series
                         0
India           New Delhi
United Kingdom     London

### Shape and Length Property

In [ ]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))

# Use the `shape` property
print(df.shape[1])
print(df.shape)
# Or use the `len()` function with the `index` property
print(len(df.index))

3
(2, 3)
2

In [ ]:
list(df.columns.values)

[0, 1, 2]

### Accesing elements of the dataframe

In [ ]:
df = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"])
print(df)

# Using `iloc[]`
print("Using iloc[]", df.iloc[0][0])

# Using `loc[]`
print("Using loc[]", df.loc[0]["B"])

# Using `at[]`
print("Using at[]", df.at[1, "C"])

# Using `iat[]`
print("Using iat[]", df.iat[2, 2])

# Using `get_value(index, column)`
print(df.get_value(1, "A"))

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
Using iloc[] 1
Using loc[] 2
Using at[] 6
Using iat[] 9
4

### Adding and Accesing an index to dataframe

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    index=[2, "A", 4],
    columns=[48, 49, 50],
)

print(df)

   48  49  50
2   1   2   3
A   4   5   6
4   7   8   9

In [ ]:
# Pass `2` to `loc`
print("Accesing you loc\n", df.loc[2])

# Pass `2` to `iloc`
print("Accessing you iloc\n", df.iloc[2])

# Pass `2` to `ix`
print("Accesing you ix\n", df.ix[2])

Accesing you loc
 48    1
49    2
50    3
Name: 2, dtype: int32
Accessing you iloc
 48    7
49    8
50    9
Name: 4, dtype: int32
Accesing you ix
 48    7
49    8
50    9
Name: 4, dtype: int32

D:\ProgramData\Anaconda\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

### Adding a row to data frame

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    index=[1, 12.6, 4.8],
    columns=[48, 49, 50],
)

print(df)
# There's No index labeled `2`,
# so you will change the index at position `2`
df.ix[2] = [60, 50, 40]
print(df)

# This will make an index labeled `2`
# and add the new values
df.loc[2] = [11, 12, 13]
print(df)

      48  49  50
1.0    1   2   3
12.6   4   5   6
4.8    7   8   9
      48  49  50
1.0    1   2   3
12.6   4   5   6
4.8   60  50  40
      48  49  50
1.0    1   2   3
12.6   4   5   6
4.8   60  50  40
2.0   11  12  13

D:\ProgramData\Anaconda\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.

### Adding a Column to data frame

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["A", "B", "C"]
)

print(df)

# Use `.index`
df["D"] = df.index

# Print `df`
print("After Adding the Column\n", df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
After Adding the Column
    A  B  C  D
0  1  2  3  0
1  4  5  6  1
2  7  8  9  2

### Another way of adding column

In [ ]:
df["E"] = [11, 12, 13]

# Print `df`
print("After Adding another Column\n", df)

df.loc[:, 3] = pd.Series(["5", "6", "7"], index=df.index)
# Print `df`
print("After Adding another Column\n", df)

After Adding another Column
    A  B  C  D   E
0  1  2  3  0  11
1  4  5  6  1  12
2  7  8  9  2  13
After Adding another Column
    A  B  C  D   E  3
0  1  2  3  0  11  5
1  4  5  6  1  12  6
2  7  8  9  2  13  7

### Resetting the index

In [ ]:
# Check out the weird index of your dataframe
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    index=[20, 30, 40],
    columns=["A", "B", "C"],
)

print(df)

# print(df.reset_index())
# Use `reset_index()` to reset the values
# print(df.reset_index(drop=True))

# Use `reset_index()` to reset the values
df.reset_index(inplace=False)
print(df)

    A  B  C
20  1  2  3
30  4  5  6
40  7  8  9
    A  B  C
20  1  2  3
30  4  5  6
40  7  8  9

### Deleting the Column

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    index=[2.5, 12.6, 4.8],
    columns=["A", "B", "C"],
)

print(df)
# Drop the column with label 'A'
# Meaning of axis attribute: Whether to drop labels from the index (0 or ‘index’) or columns (1 or ‘columns’).
df.drop("A", axis=1, inplace=True)
print("After Droping the Column \n", df)
# Drop the column at position 2
print("After Dropping another Column")
print(df.drop(df.columns[1], axis=1))

      A  B  C
2.5   1  2  3
12.6  4  5  6
4.8   7  8  9
After Droping the Column
       B  C
2.5   2  3
12.6  5  6
4.8   8  9
After Dropping another Column
      B
2.5   2
12.6  5
4.8   8

### Deleting the Row

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [7, 8, 10]]),
    index=[2.5, 12.6, 4.8, 4.8],
    columns=[48, 49, 50],
)


# Check out your DataFrame `df`
print(df)
print("\n")
# Drop the duplicates in `df`
df = pd.DataFrame(data=df.drop_duplicates([48], keep="last"))
print(df)

print("\nDrop the index at position 1")
print(df.drop(df.index[1]))

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8    7   8  10


      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8  10

Drop the index at position 1
     48  49  50
2.5   1   2   3
4.8   7   8  10

### Renaming the Index or Coulmns of Dataframe

In [ ]:
df = pd.DataFrame(
    data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [7, 8, 10]]),
    index=[2.5, 12.6, 4.8, 4.8],
    columns=[48, 49, 50],
)

print(df)
# Define the new names of your columns
newcols = {48: "A", 49: "B", 50: "C"}

# Use `rename()` to rename your columns
df.rename(columns=newcols, inplace=True)

print("After Renaming the Columns\n", df)

# Rename your index
df = pd.DataFrame(data=df.rename(index={2.5: "a"}))

print("After Renaming the Index\n", df)

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8    7   8  10
After Renaming the Columns
       A  B   C
2.5   1  2   3
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10
After Renaming the Index
       A  B   C
a     1  2   3
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10

### Basic Operations on data

In [ ]:
print(df)
df.T  # Transpose of data

      A  B   C
a     1  2   3
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10

   a  12.6  4.8  4.8
A  1     4    7    7
B  2     5    8    8
C  3     6    9   10

In [ ]:
df.sort_index(axis=1, ascending=False)  # Sorting of Columns

       C  B  A
a      3  2  1
12.6   6  5  4
4.8    9  8  7
4.8   10  8  7

In [ ]:
df.sort_values(by="B")  # Sorting of rows by Column

      A  B   C
a     1  2   3
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10

In [ ]:
# For Selecting multiple Columns
df.loc[:, ["A", "B"]]

      A  B
a     1  2
12.6  4  5
4.8   7  8
4.8   7  8

In [ ]:
# For slicing rows explicitly
df.iloc[1:3, :]

      A  B  C
12.6  4  5  6
4.8   7  8  9

In [ ]:
# For slicing cols explicitly
df.iloc[:, 1:4]

      B   C
a     2   3
12.6  5   6
4.8   8   9
4.8   8  10

### Conditional Selection

In [ ]:
df[df.A >= 4]
# df[(df.A>=4) & (df.B<8)]
# | for or

      A  B   C
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10

In [ ]:
# Selecting values from a DataFrame where a boolean condition is met.
df[df > 0]

      A  B   C
a     1  2   3
12.6  4  5   6
4.8   7  8   9
4.8   7  8  10

### Combining Data Frames
1. Concatenation
2. Merging
3. Joining

#### Lets take two data frames employee1 and employee2

In [ ]:
Eno = [100, 101, 102, 103, 104, 105]
Empname = ["Raja", "Babu", "Kumar", "Karthik", "Rajesh", "Raju"]
Eno_Series = pd.Series(Eno)
Empname_Series = pd.Series(Empname)
df = {"Eno": Eno_Series, "Empname": Empname_Series}
employee1 = pd.DataFrame(df)
employee1

   Empname  Eno
0     Raja  100
1     Babu  101
2    Kumar  102
3  Karthik  103
4   Rajesh  104
5     Raju  105

In [ ]:
Eno1 = [106, 107, 108, 109, 110]
Empname1 = ["Jack", "John", "Peter", "David", "Davis"]
Eno_Series1 = pd.Series(Eno1)
Empname_Series1 = pd.Series(Empname1)
df = {"Eno": Eno_Series1, "Empname": Empname_Series1}
employee2 = pd.DataFrame(df)
employee2

  Empname  Eno
0    Jack  106
1    John  107
2   Peter  108
3   David  109
4   Davis  110

#### Concatenation

In [ ]:
df_concat = pd.concat([employee1, employee2], ignore_index=True)
df_concat

    Empname  Eno
0      Raja  100
1      Babu  101
2     Kumar  102
3   Karthik  103
4    Rajesh  104
5      Raju  105
6      Jack  106
7      John  107
8     Peter  108
9     David  109
10    Davis  110

#### Concatenation with Key Option

In [ ]:
frames_collection = [employee1, employee2]
df_concat_keys = pd.concat(frames_collection, keys=["Section-A", "Section-B"])
df_concat_keys

             Empname  Eno
Section-A 0     Raja  100
          1     Babu  101
          2    Kumar  102
          3  Karthik  103
          4   Rajesh  104
          5     Raju  105
Section-B 0     Jack  106
          1     John  107
          2    Peter  108
          3    David  109
          4    Davis  110

#### Merging
Lets define a new dataframe designation and merge it with employee2

In [ ]:
Eno1 = [106, 107, 108, 109, 110]
Designation = [
    "Programmer",
    "Architect",
    "Project Manager",
    "Data Scientists",
    "Business Analyst",
]
Eno_Series1 = pd.Series(Eno1)
Designation_Series1 = pd.Series(Designation)
df = {"Eno": Eno_Series1, "Designation": Designation_Series1}
Designation_df = pd.DataFrame(df)
Designation_df

        Designation  Eno
0        Programmer  106
1         Architect  107
2   Project Manager  108
3   Data Scientists  109
4  Business Analyst  110

In [ ]:
df_merge_columns = pd.merge(employee2, Designation_df, on="Eno")
df_merge_columns

  Empname  Eno       Designation
0    Jack  106        Programmer
1    John  107         Architect
2   Peter  108   Project Manager
3   David  109   Data Scientists
4   Davis  110  Business Analyst

### Join Oparations

In [ ]:
# Defining two dataframes

df1 = pd.DataFrame(
    {
        "Eno": [100, 101, 102, 103, 104],
        "Ename0": ["David", "John", "Raj", "Jack", "Shantha"],
    }
)

df2 = pd.DataFrame(
    {
        "Eno": [100, 101, 102, 103, 105],
        "Salary": [1000, 1200, 1500, 1750, 2000],
        "Designation": ["Developer", "Sr.Developer", "Project Lead", "PM", "SM"],
    }
)

print(df1, "\n###########################\n", df2)

    Ename0  Eno
0    David  100
1     John  101
2      Raj  102
3     Jack  103
4  Shantha  104
###########################
     Designation  Eno  Salary
0     Developer  100    1000
1  Sr.Developer  101    1200
2  Project Lead  102    1500
3            PM  103    1750
4            SM  105    2000

#### Simple Join, By default, it is left Join

In [ ]:
df1.join(df2, lsuffix="_df1", rsuffix="_df2")

    Ename0  Eno_df1   Designation  Eno_df2  Salary
0    David      100     Developer      100    1000
1     John      101  Sr.Developer      101    1200
2      Raj      102  Project Lead      102    1500
3     Jack      103            PM      103    1750
4  Shantha      104            SM      105    2000

#### Other Joins

In [ ]:
df1 = pd.DataFrame(
    {
        "Eno": [100, 101, 102, 103, 104],
        "Ename0": ["David", "John", "Raj", "Jack", "Shantha"],
    }
)

df2 = pd.DataFrame(
    {
        "Eno": [100, 101, 102, 103, 105],
        "Salary": [1000, 1200, 1500, 1750, 2000],
        "Designation": ["Developer", "Sr.Developer", "Project Lead", "PM", "SM"],
    }
)
# Merging two dataframe using common data with common column available in both dataframe

df_join = pd.merge(df1, df2, left_on="Eno", right_on="Eno")
print(df_join)
print("\n##########################\n")

# Full Outer-"join
print("Full Outer")
df_outer = pd.merge(df1, df2, on="Eno", how="outer")
print(df_outer)
print("\n##########################\n")

# Left-Outer-join
print("Left Outer")
df_left = pd.merge(df1, df2, on="Eno", how="left")
print(df_left)
print("\n##########################\n")

# Right-Outer-join
print("Right Outer")
df_right = pd.merge(df1, df2, on="Eno", how="right")
print(df_right)
print("\n##########################\n")

# Inner-join
print("Inner ")
df_inner = pd.merge(df1, df2, on="Eno", how="inner")
print(df_inner)
print("\n##########################\n")

  Ename0  Eno   Designation  Salary
0  David  100     Developer    1000
1   John  101  Sr.Developer    1200
2    Raj  102  Project Lead    1500
3   Jack  103            PM    1750

##########################

Full Outer
    Ename0  Eno   Designation  Salary
0    David  100     Developer  1000.0
1     John  101  Sr.Developer  1200.0
2      Raj  102  Project Lead  1500.0
3     Jack  103            PM  1750.0
4  Shantha  104           NaN     NaN
5      NaN  105            SM  2000.0

##########################

Left Outer
    Ename0  Eno   Designation  Salary
0    David  100     Developer  1000.0
1     John  101  Sr.Developer  1200.0
2      Raj  102  Project Lead  1500.0
3     Jack  103            PM  1750.0
4  Shantha  104           NaN     NaN

##########################

Right Outer
  Ename0  Eno   Designation  Salary
0  David  100     Developer    1000
1   John  101  Sr.Developer    1200
2    Raj  102  Project Lead    1500
3   Jack  103            PM    1750
4    NaN  105            SM    2000

##########################

Inner
  Ename0  Eno   Designation  Salary
0  David  100     Developer    1000
1   John  101  Sr.Developer    1200
2    Raj  102  Project Lead    1500
3   Jack  103            PM    1750

##########################